import numpy as np

def se3_log(wxyz_xyz: np.ndarray) -> np.ndarray: ...
def se3_inverse_multiply(
    a_wxyz_xyz: np.ndarray, b_wxyz_xyz: np.ndarray
) -> np.ndarray: ...
def se3_rminus(a_wxyz_xyz: np.ndarray, b_wxyz_xyz: np.ndarray) -> np.ndarray: ...
def se3_jlog(wxyz_xyz: np.ndarray) -> np.ndarray: ...
def se3_adjoint(wxyz_xyz: np.ndarray) -> np.ndarray: ...
def se3_rotation_adjoint_from_xmat(xmat: np.ndarray) -> np.ndarray: ...
